image: 
  file: .gitpod.Dockerfile

tasks:
  # - init: /usr/bin/start-vnc-session.sh
  - command: zsh
  - command: cd .. && jupyter-lab --ContentsManager.allow_hidden=True

# Ports to expose on workspace startup
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: ignore
  - port: 8888
    onOpen: open-preview
